const SQLITE_SCHEMA = [
    `CREATE TABLE IF NOT EXISTS orders (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT UNIQUE,
        customer_name TEXT,
        customer_email TEXT,
        customer_phone TEXT,
        shipping_address TEXT,
        city TEXT,
        country TEXT,
        status TEXT DEFAULT 'draft',
        total_amount REAL,
        currency TEXT DEFAULT 'GBP',
        payment_ref TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id INTEGER,
        suit_name TEXT,
        gender TEXT,
        measurements TEXT,
        price REAL,
        FOREIGN KEY (order_id) REFERENCES orders (id)
    )`,
    `CREATE TABLE IF NOT EXISTS bookings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT NOT NULL,
        booking_date TEXT NOT NULL,
        booking_time TEXT NOT NULL,
        notes TEXT,
        region TEXT DEFAULT 'Jamaica',
        status TEXT DEFAULT 'confirmed',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(booking_date, booking_time)
    )`,
    `CREATE TABLE IF NOT EXISTS deposit_sessions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        deposit_id TEXT UNIQUE,
        customer_name TEXT,
        customer_email TEXT,
        customer_phone TEXT,
        design_data TEXT,
        amount REAL DEFAULT 30000,
        currency TEXT DEFAULT 'JMD',
        status TEXT DEFAULT 'pending',
        payment_ref TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS unavailable_slots (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        block_type TEXT NOT NULL,
        block_date TEXT NOT NULL,
        block_time TEXT,
        reason TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS design_inquiries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        customer_name TEXT NOT NULL,
        customer_email TEXT NOT NULL,
        customer_phone TEXT,
        design_name TEXT,
        gender TEXT,
        fabric TEXT,
        target_date TEXT,
        description TEXT,
        booking_date TEXT,
        booking_time TEXT,
        has_photo INTEGER DEFAULT 0,
        status TEXT DEFAULT 'new',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS custom_invoices (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        invoice_number TEXT UNIQUE NOT NULL,
        customer_name TEXT NOT NULL DEFAULT 'Valued Client',
        customer_email TEXT,
        customer_phone TEXT,
        whatsapp_phone TEXT,
        customer_address TEXT,
        issue_date TEXT NOT NULL,
        due_date TEXT,
        currency TEXT DEFAULT 'JMD',
        line_items TEXT NOT NULL,
        subtotal_amount REAL DEFAULT 0,
        tax_amount REAL DEFAULT 0,
        total_amount REAL DEFAULT 0,
        deposit_percentage REAL DEFAULT 0,
        deposit_amount REAL DEFAULT 0,
        amount_paid REAL DEFAULT 0,
        amount_paid_percentage REAL DEFAULT 0,
        balance_due REAL DEFAULT 0,
        payment_status TEXT DEFAULT 'unpaid',
        notes TEXT,
        pdf_path TEXT,
        last_sent_at DATETIME,
        last_sent_to TEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_bookings_date_status ON bookings (booking_date, status)`,
    `CREATE INDEX IF NOT EXISTS idx_bookings_status_date_time ON bookings (status, booking_date, booking_time)`,
    `CREATE INDEX IF NOT EXISTS idx_deposit_sessions_status_created_at ON deposit_sessions (status, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_unavailable_slots_date ON unavailable_slots (block_date)`,
    `CREATE INDEX IF NOT EXISTS idx_design_inquiries_status_created_at ON design_inquiries (status, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_custom_invoices_created_at ON custom_invoices (created_at)`
];

const POSTGRES_SCHEMA = [
    `CREATE TABLE IF NOT EXISTS orders (
        id SERIAL PRIMARY KEY,
        session_id TEXT UNIQUE,
        customer_name TEXT,
        customer_email TEXT,
        customer_phone TEXT,
        shipping_address TEXT,
        city TEXT,
        country TEXT,
        status TEXT DEFAULT 'draft',
        total_amount DOUBLE PRECISION,
        currency TEXT DEFAULT 'GBP',
        payment_ref TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_items (
        id SERIAL PRIMARY KEY,
        order_id INTEGER REFERENCES orders (id),
        suit_name TEXT,
        gender TEXT,
        measurements TEXT,
        price DOUBLE PRECISION
    )`,
    `CREATE TABLE IF NOT EXISTS bookings (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT NOT NULL,
        booking_date TEXT NOT NULL,
        booking_time TEXT NOT NULL,
        notes TEXT,
        region TEXT DEFAULT 'Jamaica',
        status TEXT DEFAULT 'confirmed',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(booking_date, booking_time)
    )`,
    `CREATE TABLE IF NOT EXISTS deposit_sessions (
        id SERIAL PRIMARY KEY,
        deposit_id TEXT UNIQUE,
        customer_name TEXT,
        customer_email TEXT,
        customer_phone TEXT,
        design_data TEXT,
        amount DOUBLE PRECISION DEFAULT 30000,
        currency TEXT DEFAULT 'JMD',
        status TEXT DEFAULT 'pending',
        payment_ref TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS unavailable_slots (
        id SERIAL PRIMARY KEY,
        block_type TEXT NOT NULL,
        block_date TEXT NOT NULL,
        block_time TEXT,
        reason TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS design_inquiries (
        id SERIAL PRIMARY KEY,
        customer_name TEXT NOT NULL,
        customer_email TEXT NOT NULL,
        customer_phone TEXT,
        design_name TEXT,
        gender TEXT,
        fabric TEXT,
        target_date TEXT,
        description TEXT,
        booking_date TEXT,
        booking_time TEXT,
        has_photo INTEGER DEFAULT 0,
        status TEXT DEFAULT 'new',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS custom_invoices (
        id SERIAL PRIMARY KEY,
        invoice_number TEXT UNIQUE NOT NULL,
        customer_name TEXT NOT NULL DEFAULT 'Valued Client',
        customer_email TEXT,
        customer_phone TEXT,
        whatsapp_phone TEXT,
        customer_address TEXT,
        issue_date TEXT NOT NULL,
        due_date TEXT,
        currency TEXT DEFAULT 'JMD',
        line_items TEXT NOT NULL,
        subtotal_amount DOUBLE PRECISION DEFAULT 0,
        tax_amount DOUBLE PRECISION DEFAULT 0,
        total_amount DOUBLE PRECISION DEFAULT 0,
        deposit_percentage DOUBLE PRECISION DEFAULT 0,
        deposit_amount DOUBLE PRECISION DEFAULT 0,
        amount_paid DOUBLE PRECISION DEFAULT 0,
        amount_paid_percentage DOUBLE PRECISION DEFAULT 0,
        balance_due DOUBLE PRECISION DEFAULT 0,
        payment_status TEXT DEFAULT 'unpaid',
        notes TEXT,
        pdf_path TEXT,
        last_sent_at TIMESTAMP,
        last_sent_to TEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_bookings_date_status ON bookings (booking_date, status)`,
    `CREATE INDEX IF NOT EXISTS idx_bookings_status_date_time ON bookings (status, booking_date, booking_time)`,
    `CREATE INDEX IF NOT EXISTS idx_deposit_sessions_status_created_at ON deposit_sessions (status, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_unavailable_slots_date ON unavailable_slots (block_date)`,
    `CREATE INDEX IF NOT EXISTS idx_design_inquiries_status_created_at ON design_inquiries (status, created_at)`,
    `CREATE INDEX IF NOT EXISTS idx_custom_invoices_created_at ON custom_invoices (created_at)`
];

module.exports = {
    SQLITE_SCHEMA,
    POSTGRES_SCHEMA
};
